import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { TripPlan } from '../types';

interface User {
  uid: string;
  email: string | null;
  displayName: string | null;
}

interface StoreState {
  language: 'es' | 'en' | 'de' | 'ru';
  favorites: string[];
  user: User | null;
  tripPlans: TripPlan[];
  activePlanId: string | null;
  setLanguage: (lang: 'es' | 'en' | 'de' | 'ru') => void;
  addToFavorites: (id: string) => void;
  removeFromFavorites: (id: string) => void;
  isFavorite: (id: string) => boolean;
  setUser: (user: User | null) => void;
  createPlan: (name: string, startDate: string, endDate: string) => string;
  deletePlan: (planId: string) => void;
  setActivePlan: (planId: string | null) => void;
  addBusinessToDay: (planId: string, dayId: string, businessId: string) => void;
  removeBusinessFromDay: (planId: string, dayId: string, businessId: string) => void;
  updateDayNotes: (planId: string, dayId: string, notes: string) => void;
  renamePlan: (planId: string, name: string) => void;
}

export const useStore = create<StoreState>()(
  persist(
    (set, get) => ({
      language: 'en',
      favorites: [],
      user: null,
      tripPlans: [],
      activePlanId: null,
      setLanguage: (lang) => set({ language: lang }),
      addToFavorites: (id) => set((state) => ({ favorites: [...state.favorites, id] })),
      removeFromFavorites: (id) => set((state) => ({ favorites: state.favorites.filter((f) => f !== id) })),
      isFavorite: (id) => get().favorites.includes(id),
      setUser: (user) => set({ user }),
      createPlan: (name, startDate, endDate) => {
        const id = 'plan_' + Date.now();
        const start = new Date(startDate);
        const end = new Date(endDate);
        const days: TripPlan['days'] = [];
        const dayLabels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
        const current = new Date(start);
        while (current <= end) {
          const dateStr = current.toISOString().split('T')[0];
          days.push({
            id: 'day_' + dateStr,
            date: dateStr,
            label: dayLabels[current.getDay()],
            businessIds: [],
          });
          current.setDate(current.getDate() + 1);
        }
        const plan: TripPlan = { id, name, startDate, endDate, days, createdAt: new Date().toISOString() };
        set((state) => ({ tripPlans: [...state.tripPlans, plan], activePlanId: id }));
        return id;
      },
      deletePlan: (planId) => set((state) => ({
        tripPlans: state.tripPlans.filter((p) => p.id !== planId),
        activePlanId: state.activePlanId === planId ? null : state.activePlanId,
      })),
      setActivePlan: (planId) => set({ activePlanId: planId }),
      addBusinessToDay: (planId, dayId, businessId) => set((state) => ({
        tripPlans: state.tripPlans.map((p) =>
          p.id !== planId ? p : {
            ...p,
            days: p.days.map((d) =>
              d.id !== dayId ? d : { ...d, businessIds: [...new Set([...d.businessIds, businessId])] }
            ),
          }
        ),
      })),
      removeBusinessFromDay: (planId, dayId, businessId) => set((state) => ({
        tripPlans: state.tripPlans.map((p) =>
          p.id !== planId ? p : {
            ...p,
            days: p.days.map((d) =>
              d.id !== dayId ? d : { ...d, businessIds: d.businessIds.filter((b) => b !== businessId) }
            ),
          }
        ),
      })),
      updateDayNotes: (planId, dayId, notes) => set((state) => ({
        tripPlans: state.tripPlans.map((p) =>
          p.id !== planId ? p : {
            ...p,
            days: p.days.map((d) =>
              d.id !== dayId ? d : { ...d, notes }
            ),
          }
        ),
      })),
      renamePlan: (planId, name) => set((state) => ({
        tripPlans: state.tripPlans.map((p) =>
          p.id !== planId ? p : { ...p, name }
        ),
      })),
    }),
    { name: 'mallorca-storage' }
  )
);

export const translations = {
  es: {
    title: 'Directorio Mallorca',
    subtitle: 'Descubre los mejores negocios',
    search: 'Buscar...',
    categories: 'Categorías',
    favorites: 'Favoritos',
    profile: 'Perfil',
    language: 'Idioma',
    settings: 'Configuración',
    addToFavorites: 'Añadido a favoritos',
    removeFromFavorites: 'Eliminado de favoritos',
    verified: 'Verificado',
    loading: 'Cargando...',
    noBusinesses: 'No hay negocios',
    hours: 'Horario',
    noBusinessesInCategory: 'No hay negocios en esta categoría',
    noBusinessesInArea: 'No hay negocios en esta zona',
    areas: 'Zonas',
    businesses: 'Negocios',
    places: 'Lugares',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    signOut: 'Cerrar sesión',
    email: 'Correo electrónico',
    password: 'Contraseña',
    addBusiness: 'Añadir empresa',
    businessName: 'Nombre de la empresa',
    phone: 'Teléfono',
    website: 'Sitio web',
    description: 'Descripción',
    address: 'Dirección',
    submit: 'Enviar',
    about: 'Acerca de',
    version: 'Versión',
    privacy: 'Política de privacidad',
    help: 'Ayuda y soporte',
    events: 'Eventos',
    guides: 'Guías',
    tripPlanner: 'Planificador',
    planner: 'Plan de Viaje',
    plannerSub: 'Organiza tus días en Mallorca',
    newPlan: 'Nuevo Plan',
    planName: 'Nombre del viaje...',
    noPlans: 'Sin planes aún',
    noPlansSub: 'Crea tu primer plan de viaje',
    deletePlan: 'Eliminar Plan',
    deletePlanConfirm: '¿Estás seguro? Esta acción no se puede deshacer.',
    plannerDateError: 'La fecha de inicio debe ser anterior a la fecha de fin',
    dayEmpty: 'Nada planificado aún',
    dayEmptySub: 'Toca + para añadir negocios y eventos a este día',
    addPlace: 'Añadir Lugar',
    viewDetails: 'Ver detalles',
    editNotes: 'Editar notas',
    addNotes: 'Añadir notas',
    notesPlaceholder: 'Escribe tus notas aquí...',
    noResults: 'Sin resultados',
    savedPlaces: 'lugares guardados',
    noFavorites: 'Sin favoritos',
    noFavoritesSub: 'Empieza a explorar y guarda tus sitios favoritos',
    premium: 'Premium',
    claim: 'Reclamar negocio',
    claimed: 'Reclamado',
    claimBusiness: '¿Es tuyo este negocio?',
    claimInfo: 'Verifica que eres el propietario y gestiona tus datos',
    claimRequested: 'Solicitud enviada',
    startDate: 'Fecha inicio',
    endDate: 'Fecha fin',
    allCategories: 'Todas las categorías',
    loadMore: 'Cargar más',
    noEvents: 'No hay eventos',
    noGuides: 'No hay guías',
    readMore: 'Leer más',
    planTrip: 'Planificar viaje',
    myPlans: 'Mis planes',
    addToPlan: 'Añadir al plan',
    removeFromPlan: 'Quitar del plan',
    day: 'Día',
    addDay: 'Añadir día',
    notes: 'Notas',
    premiumPartner: 'Partner Premium',
    claimNow: 'Reclamar ahora',
    callToAction: 'Llamar',
    getDirections: 'Cómo llegar',
    share: 'Compartir',
    all: 'Todo',
    months: 'Meses',
    today: 'Hoy',
    tomorrow: 'Mañana',
    past: 'Pasado',
    days: 'días',
    read: 'leer',
    eventsSub: 'Descubre eventos, festivales y actividades en Mallorca',
    emptyEventsSub: 'Vuelve más tarde para ver nuevos eventos',
    guidesSub: 'Guías expertas para vivir, viajar y disfrutar Mallorca',
    emptyGuidesSub: 'Vuelve más tarde para ver nuevas guías',
    eventNotFound: 'Evento no encontrado',
    guideNotFound: 'Guía no encontrada',
    view: 'Ver',
    discoverMallorca: 'Descubre Mallorca',
    homeSubtitle: 'Encuentra eventos, restaurantes, tours y servicios de confianza en Mallorca en un solo lugar.',
    selectDateRange: 'Seleccionar fechas',
    entities: 'Entidades',
    totalEntries: 'Total entradas',
    reviews: 'Reseñas',
    popularCategories: 'Categorías Populares',
    popularCategoriesSub: 'Descubre las categorías más populares en Mallorca',
    premiumPartners: 'Socios Premium',
    viewAll: 'Ver todo',
    exploreByArea: 'Explorar por Zona',
    entries: 'Entradas',
    plannerCtaTitle: 'Planificador de Viajes y Actividades Mallorca',
    plannerCtaSub: 'Planifica tus días en Mallorca como un calendario — añade eventos y lugares reales, crea tus propias franjas y compártelo como una suscripción de calendario.',
    tryItFree: 'Pruébalo gratis →',
    explore: 'Explorar',
    footerTagline: 'Tu guía completa de Mallorca',
    footerFoodDrink: 'Comida y Bebida',
    footerServices: 'Servicios',
    footerLocations: 'Ubicaciones',
    footerEvents: 'Eventos',
    footerActivities: 'Actividades',
    footerMoving: 'Mudanza a Mallorca',
    footerFormentor: 'Formentor 2026',
    footerTax: 'Impuesto Turístico',
    footerCar: 'Matricular Coche',
    footerNIE: 'Número NIE',
    footerApp: 'También como app',
    footerAppStore: 'App Store',
    footerGooglePlay: 'Google Play',
    footerImprint: 'Aviso Legal',
    footerCopyright: 'Reservados todos los derechos',
    open: 'Abrir',
    back: 'Atrás',
    delete: 'Eliminar',
    create: 'Crear',
    save: 'Guardar',
    cancel: 'Cancelar',
  },
  en: {
    title: 'Mallorca Directory',
    subtitle: 'Discover the best businesses',
    search: 'Search...',
    categories: 'Categories',
    favorites: 'Favorites',
    profile: 'Profile',
    language: 'Language',
    settings: 'Settings',
    addToFavorites: 'Added to favorites',
    removeFromFavorites: 'Removed from favorites',
    verified: 'Verified',
    loading: 'Loading...',
    noBusinesses: 'No businesses',
    hours: 'Hours',
    noBusinessesInCategory: 'No businesses in this category',
    noBusinessesInArea: 'No businesses in this area',
    areas: 'Areas',
    businesses: 'Businesses',
    places: 'Places',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    email: 'Email',
    password: 'Password',
    addBusiness: 'Add Business',
    businessName: 'Business Name',
    phone: 'Phone',
    website: 'Website',
    description: 'Description',
    address: 'Address',
    submit: 'Submit',
    about: 'About',
    version: 'Version',
    privacy: 'Privacy Policy',
    help: 'Help & Support',
    events: 'Events',
    guides: 'Guides',
    tripPlanner: 'Trip Planner',
    planner: 'Trip Plan',
    plannerSub: 'Organize your days on Mallorca',
    newPlan: 'New Plan',
    planName: 'Trip name...',
    noPlans: 'No plans yet',
    noPlansSub: 'Create your first trip plan to get started',
    deletePlan: 'Delete Plan',
    deletePlanConfirm: 'Are you sure? This cannot be undone.',
    plannerDateError: 'Start date must be before end date',
    dayEmpty: 'Nothing planned yet',
    dayEmptySub: 'Tap + to add businesses and events to this day',
    addPlace: 'Add Place',
    viewDetails: 'View details',
    editNotes: 'Edit notes',
    addNotes: 'Add notes',
    notesPlaceholder: 'Write your notes here...',
    noResults: 'No results found',
    savedPlaces: 'saved places',
    noFavorites: 'No favorites yet',
    noFavoritesSub: 'Start exploring and save your favorite places',
    premium: 'Premium',
    claim: 'Claim Business',
    claimed: 'Claimed',
    claimBusiness: 'Is this yours?',
    claimInfo: 'Verify ownership and manage your data',
    claimRequested: 'Request submitted',
    startDate: 'Start Date',
    endDate: 'End Date',
    allCategories: 'All Categories',
    loadMore: 'Load More',
    noEvents: 'No events found',
    noGuides: 'No guides yet',
    readMore: 'Read More',
    planTrip: 'Plan Your Trip',
    myPlans: 'My Plans',
    addToPlan: 'Add to Plan',
    removeFromPlan: 'Remove from Plan',
    day: 'Day',
    addDay: 'Add Day',
    notes: 'Notes',
    premiumPartner: 'Premium Partner',
    claimNow: 'Claim Now',
    callToAction: 'Call',
    getDirections: 'Get Directions',
    share: 'Share',
    all: 'All',
    months: 'Months',
    today: 'Today',
    tomorrow: 'Tomorrow',
    past: 'Past',
    days: 'days',
    read: 'read',
    eventsSub: 'Discover events, festivals and activities across Mallorca',
    emptyEventsSub: 'Check back later for new events and offers',
    guidesSub: 'Expert guides to help you live, travel and enjoy Mallorca',
    emptyGuidesSub: 'Check back later for new guides',
    eventNotFound: 'Event not found',
    guideNotFound: 'Guide not found',
    view: 'View',
    discoverMallorca: 'Discover Mallorca',
    homeSubtitle: 'Find events, restaurants, tours and trusted services in Mallorca in one place.',
    selectDateRange: 'Select date range',
    entities: 'Entities',
    totalEntries: 'Total entries',
    reviews: 'Reviews',
    popularCategories: 'Popular Categories',
    popularCategoriesSub: 'Discover the most popular categories in Mallorca',
    premiumPartners: 'Premium Partners',
    viewAll: 'View all',
    exploreByArea: 'Explore by Area',
    entries: 'Entries',
    plannerCtaTitle: 'Mallorca Trip & Activity Planner',
    plannerCtaSub: 'Plan your Mallorca days like a calendar — add real events & places, create your own slots, and share it as a calendar subscription.',
    tryItFree: 'Try it free →',
    explore: 'Explore',
    footerTagline: 'Your comprehensive guide to Mallorca',
    footerFoodDrink: 'Food & Drink',
    footerServices: 'Services',
    footerLocations: 'Locations',
    footerEvents: 'Events',
    footerActivities: 'Activities',
    footerMoving: 'Moving to Mallorca',
    footerFormentor: 'Formentor 2026',
    footerTax: 'Tourist Tax',
    footerCar: 'Car Registration',
    footerNIE: 'NIE Number',
    footerApp: 'Also as an app',
    footerAppStore: 'App Store',
    footerGooglePlay: 'Google Play',
    footerImprint: 'Imprint',
    footerCopyright: 'All rights reserved',
    open: 'Open',
    back: 'Back',
    delete: 'Delete',
    create: 'Create',
    save: 'Save',
    cancel: 'Cancel',
  },
  de: {
    title: 'Mallorca Verzeichnis',
    subtitle: 'Entdecken Sie die besten Geschäfte',
    search: 'Suchen...',
    categories: 'Kategorien',
    favorites: 'Favoriten',
    profile: 'Profil',
    language: 'Sprache',
    settings: 'Einstellungen',
    addToFavorites: 'Zu Favoriten hinzugefügt',
    removeFromFavorites: 'Aus Favoriten entfernt',
    verified: 'Verifiziert',
    loading: 'Wird geladen...',
    noBusinesses: 'Keine Unternehmen',
    hours: 'Öffnungszeiten',
    noBusinessesInCategory: 'Keine Unternehmen in dieser Kategorie',
    noBusinessesInArea: 'Keine Unternehmen in diesem Bereich',
    areas: 'Gebiete',
    businesses: 'Unternehmen',
    places: 'Orte',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    signOut: 'Abmelden',
    email: 'E-Mail',
    password: 'Passwort',
    addBusiness: 'Unternehmen hinzufügen',
    businessName: 'Unternehmensname',
    phone: 'Telefon',
    website: 'Webseite',
    description: 'Beschreibung',
    address: 'Adresse',
    submit: 'Absenden',
    about: 'Über',
    version: 'Version',
    privacy: 'Datenschutz',
    help: 'Hilfe & Support',
    events: 'Veranstaltungen',
    guides: 'Ratgeber',
    tripPlanner: 'Reiseplaner',
    planner: 'Reiseplan',
    plannerSub: 'Organisieren Sie Ihre Tage auf Mallorca',
    newPlan: 'Neuer Plan',
    planName: 'Reisename...',
    noPlans: 'Noch keine Pläne',
    noPlansSub: 'Erstellen Sie Ihren ersten Reiseplan',
    deletePlan: 'Plan löschen',
    deletePlanConfirm: 'Sind Sie sicher? Dies kann nicht rückgängig gemacht werden.',
    plannerDateError: 'Startdatum muss vor Enddatum liegen',
    dayEmpty: 'Noch nichts geplant',
    dayEmptySub: 'Tippen Sie auf +, um Unternehmen und Veranstaltungen hinzuzufügen',
    addPlace: 'Ort hinzufügen',
    viewDetails: 'Details anzeigen',
    editNotes: 'Notizen bearbeiten',
    addNotes: 'Notizen hinzufügen',
    notesPlaceholder: 'Schreiben Sie Ihre Notizen hier...',
    noResults: 'Keine Ergebnisse gefunden',
    savedPlaces: 'gespeicherte Orte',
    noFavorites: 'Keine Favoriten',
    noFavoritesSub: 'Beginnen Sie mit der Erkundung und speichern Sie Ihre Lieblingsorte',
    premium: 'Premium',
    claim: 'Unternehmen beanspruchen',
    claimed: 'Beansprucht',
    claimBusiness: 'Gehört Ihnen das?',
    claimInfo: 'Bestätigen Sie Ihre Inhaberschaft und verwalten Sie Ihre Daten',
    claimRequested: 'Anfrage gesendet',
    startDate: 'Startdatum',
    endDate: 'Enddatum',
    allCategories: 'Alle Kategorien',
    loadMore: 'Mehr laden',
    noEvents: 'Keine Veranstaltungen',
    noGuides: 'Keine Ratgeber',
    readMore: 'Weiterlesen',
    planTrip: 'Reise planen',
    myPlans: 'Meine Pläne',
    addToPlan: 'Zum Plan hinzufügen',
    removeFromPlan: 'Vom Plan entfernen',
    day: 'Tag',
    addDay: 'Tag hinzufügen',
    notes: 'Notizen',
    premiumPartner: 'Premium Partner',
    claimNow: 'Jetzt beanspruchen',
    callToAction: 'Anrufen',
    getDirections: 'Route',
    share: 'Teilen',
    all: 'Alle',
    months: 'Monate',
    today: 'Heute',
    tomorrow: 'Morgen',
    past: 'Vergangen',
    days: 'Tage',
    read: 'Lesen',
    eventsSub: 'Entdecken Sie Veranstaltungen, Feste und Aktivitäten auf Mallorca',
    emptyEventsSub: 'Schauen Sie später vorbei für neue Veranstaltungen',
    guidesSub: 'Expertenratgeber zum Leben, Reisen und Genießen auf Mallorca',
    emptyGuidesSub: 'Schauen Sie später vorbei für neue Ratgeber',
    eventNotFound: 'Veranstaltung nicht gefunden',
    guideNotFound: 'Ratgeber nicht gefunden',
    view: 'Ansehen',
    discoverMallorca: 'Mallorca entdecken',
    homeSubtitle: 'Finden Sie Veranstaltungen, Restaurants, Touren und vertrauenswürdige Dienstleistungen auf Mallorca an einem Ort.',
    selectDateRange: 'Zeitraum wählen',
    entities: 'Einträge',
    totalEntries: 'Gesamteinträge',
    reviews: 'Bewertungen',
    popularCategories: 'Beliebte Kategorien',
    popularCategoriesSub: 'Entdecken Sie die beliebtesten Kategorien auf Mallorca',
    premiumPartners: 'Premium Partner',
    viewAll: 'Alle anzeigen',
    exploreByArea: 'Nach Gebiet erkunden',
    entries: 'Einträge',
    plannerCtaTitle: 'Mallorca Reise- & Aktivitätenplaner',
    plannerCtaSub: 'Planen Sie Ihre Mallorca-Tage wie einen Kalender — fügen Sie echte Events & Orte hinzu, erstellen Sie eigene Slots und teilen Sie es als Kalenderabonnement.',
    tryItFree: 'Kostenlos testen →',
    explore: 'Erkunden',
    footerTagline: 'Ihr umfassender Reiseführer für Mallorca',
    footerFoodDrink: 'Essen & Trinken',
    footerServices: 'Dienstleistungen',
    footerLocations: 'Orte',
    footerEvents: 'Veranstaltungen',
    footerActivities: 'Aktivitäten',
    footerMoving: 'Umzug nach Mallorca',
    footerFormentor: 'Formentor 2026',
    footerTax: 'Touristensteuer',
    footerCar: 'Auto anmelden',
    footerNIE: 'NIE-Nummer',
    footerApp: 'Auch als App',
    footerAppStore: 'App Store',
    footerGooglePlay: 'Google Play',
    footerImprint: 'Impressum',
    footerCopyright: 'Alle Rechte vorbehalten',
    open: 'Öffnen',
    back: 'Zurück',
    delete: 'Löschen',
    create: 'Erstellen',
    save: 'Speichern',
    cancel: 'Abbrechen',
  },
  ru: {
    title: 'Директория Майорки',
    subtitle: 'Откройте лучшие заведения',
    search: 'Поиск...',
    categories: 'Категории',
    favorites: 'Избранное',
    profile: 'Профиль',
    language: 'Язык',
    settings: 'Настройки',
    addToFavorites: 'Добавлено в избранное',
    removeFromFavorites: 'Удалено из избранного',
    verified: 'Проверено',
    loading: 'Загрузка...',
    noBusinesses: 'Нет заведений',
    hours: 'Часы работы',
    noBusinessesInCategory: 'Нет заведений в этой категории',
    noBusinessesInArea: 'Нет заведений в этой зоне',
    areas: 'Районы',
    businesses: 'Заведения',
    places: 'Места',
    signIn: 'Войти',
    signUp: 'Регистрация',
    signOut: 'Выйти',
    email: 'Email',
    password: 'Пароль',
    addBusiness: 'Добавить компанию',
    businessName: 'Название компании',
    phone: 'Телефон',
    website: 'Сайт',
    description: 'Описание',
    address: 'Адрес',
    submit: 'Отправить',
    about: 'О приложении',
    version: 'Версия',
    privacy: 'Политика конфиденциальности',
    help: 'Помощь и поддержка',
    events: 'События',
    guides: 'Гайды',
    tripPlanner: 'Планировщик',
    planner: 'План поездки',
    plannerSub: 'Организуйте свои дни на Мальорке',
    newPlan: 'Новый план',
    planName: 'Название поездки...',
    noPlans: 'Пока нет планов',
    noPlansSub: 'Создайте свой первый план поездки',
    deletePlan: 'Удалить план',
    deletePlanConfirm: 'Вы уверены? Это действие нельзя отменить.',
    plannerDateError: 'Дата начала должна быть раньше даты окончания',
    dayEmpty: 'Пока ничего не запланировано',
    dayEmptySub: 'Нажмите +, чтобы добавить места и события в этот день',
    addPlace: 'Добавить место',
    viewDetails: 'Подробнее',
    editNotes: 'Редактировать заметки',
    addNotes: 'Добавить заметки',
    notesPlaceholder: 'Напишите свои заметки здесь...',
    noResults: 'Ничего не найдено',
    savedPlaces: 'сохранённых мест',
    noFavorites: 'Нет избранного',
    noFavoritesSub: 'Начните исследовать и сохраняйте любимые места',
    premium: 'Премиум',
    claim: 'Заявить бизнес',
    claimed: 'Заявлено',
    claimBusiness: 'Это ваш бизнес?',
    claimInfo: 'Подтвердите владение и управляйте данными',
    claimRequested: 'Запрос отправлен',
    startDate: 'Дата начала',
    endDate: 'Дата окончания',
    allCategories: 'Все категории',
    loadMore: 'Загрузить ещё',
    noEvents: 'Нет событий',
    noGuides: 'Нет гайдов',
    readMore: 'Читать далее',
    planTrip: 'Спланировать поездку',
    myPlans: 'Мои планы',
    addToPlan: 'Добавить в план',
    removeFromPlan: 'Убрать из плана',
    day: 'День',
    addDay: 'Добавить день',
    notes: 'Заметки',
    premiumPartner: 'Премиум-партнёр',
    claimNow: 'Заявить сейчас',
    callToAction: 'Позвонить',
    getDirections: 'Маршрут',
    share: 'Поделиться',
    all: 'Все',
    months: 'Месяцы',
    today: 'Сегодня',
    tomorrow: 'Завтра',
    past: 'Прошедшие',
    days: 'дней',
    read: 'чтение',
    eventsSub: 'Откройте для себя события, фестивали и развлечения по всей Мальорке',
    emptyEventsSub: 'Загляните позже — появятся новые события',
    guidesSub: 'Экспертные гиды, чтобы жить, путешествовать и наслаждаться Мальоркой',
    emptyGuidesSub: 'Загляните позже — появятся новые гиды',
    eventNotFound: 'Событие не найдено',
    guideNotFound: 'Гид не найден',
    view: 'Просмотр',
    discoverMallorca: 'Откройте Мальорку',
    homeSubtitle: 'Находите события, рестораны, туры и надёжные услуги на Мальорке в одном месте.',
    selectDateRange: 'Выберите даты',
    entities: 'Объекты',
    totalEntries: 'Всего записей',
    reviews: 'Отзывы',
    popularCategories: 'Популярные категории',
    popularCategoriesSub: 'Откройте самые популярные категории на Мальорке',
    premiumPartners: 'Премиум-партнёры',
    viewAll: 'Смотреть всё',
    exploreByArea: 'Исследовать по районам',
    entries: 'Записей',
    plannerCtaTitle: 'Планировщик поездок Мальорки',
    plannerCtaSub: 'Планируйте дни на Мальорке как календарь — добавляйте реальные события и места, создавайте свои слоты и делитесь календарём.',
    tryItFree: 'Попробовать бесплатно →',
    explore: 'Исследовать',
    footerTagline: 'Ваш полный путеводитель по Мальорке',
    footerFoodDrink: 'Еда и напитки',
    footerServices: 'Услуги',
    footerLocations: 'Места',
    footerEvents: 'События',
    footerActivities: 'Развлечения',
    footerMoving: 'Переезд на Мальорку',
    footerFormentor: 'Форментор 2026',
    footerTax: 'Туристический налог',
    footerCar: 'Регистрация авто',
    footerNIE: 'Номер NIE',
    footerApp: 'Также как приложение',
    footerAppStore: 'App Store',
    footerGooglePlay: 'Google Play',
    footerImprint: 'Выходные данные',
    footerCopyright: 'Все права защищены',
    open: 'Открыть',
    back: 'Назад',
    delete: 'Удалить',
    create: 'Создать',
    save: 'Сохранить',
    cancel: 'Отмена',
  },
};

export const categoryTranslations: Record<string, Record<string, string>> = {
  es: {
    restaurants: 'Restaurantes', cafes: 'Cafeterías', hotels: 'Hoteles',
    beaches: 'Playas', parks: 'Parques', activities: 'Actividades',
    shopping: 'Tiendas', supermarkets: 'Supermercados', services: 'Servicios',
    transport: 'Transporte', health: 'Hospitales', pharmacies: 'Farmacias',
    police: 'Policía', gasstations: 'Gasolineras', veterinarians: 'Veterinarios',
    banks: 'Bancos', postoffice: 'Correos', industrial: 'Polígonos Industriales',
  },
  en: {
    restaurants: 'Restaurants', cafes: 'Cafés', hotels: 'Hotels',
    beaches: 'Beaches', parks: 'Parks', activities: 'Activities',
    shopping: 'Shopping', supermarkets: 'Supermarkets', services: 'Services',
    transport: 'Transport', health: 'Hospitals', pharmacies: 'Pharmacies',
    police: 'Police', gasstations: 'Gas Stations', veterinarians: 'Veterinarians',
    banks: 'Banks', postoffice: 'Post Office', industrial: 'Industrial Estates',
  },
  de: {
    restaurants: 'Restaurants', cafes: 'Cafés', hotels: 'Hotels',
    beaches: 'Strände', parks: 'Parks', activities: 'Aktivitäten',
    shopping: 'Einkaufen', supermarkets: 'Supermärkte', services: 'Dienstleistungen',
    transport: 'Verkehr', health: 'Krankenhäuser', pharmacies: 'Apotheken',
    police: 'Polizei', gasstations: 'Tankstellen', veterinarians: 'Tierärzte',
    banks: 'Banken', postoffice: 'Post', industrial: 'Industriegebiete',
  },
  ru: {
    restaurants: 'Рестораны', cafes: 'Кафе', hotels: 'Отели',
    beaches: 'Пляжи', parks: 'Парки', activities: 'Развлечения',
    shopping: 'Магазины', supermarkets: 'Супермаркеты', services: 'Услуги',
    transport: 'Транспорт', health: 'Больницы', pharmacies: 'Аптеки',
    police: 'Полиция', gasstations: 'Заправки', veterinarians: 'Ветеринары',
    banks: 'Банки', postoffice: 'Почта', industrial: 'Промышленные зоны',
  },
};

export const subcategoryTranslations: Record<string, Record<string, string>> = {
  es: {
    Italian: 'Italiano', Spanish: 'Español', Asian: 'Asiático', German: 'Alemán', International: 'Internacional',
    Pizza: 'Pizza', Sushi: 'Sushi', Tapas: 'Tapas', Seafood: 'Mariscos', Brunch: 'Brunch',
    Vegetarian: 'Vegetariano', 'Fine Dining': 'Alta Cocina',
    Coffee: 'Café', 'Tea House': 'Casa de Té', Bakery: 'Panadería', 'Cocktail Bar': 'Coctelería', 'Wine Bar': 'Bar de Vinos',
    '5 Star': '5 Estrellas', '4 Star': '4 Estrellas', '3 Star': '3 Estrellas',
    Boutique: 'Boutique', Resort: 'Complejo Turístico', Agrotourism: 'Agroturismo', Apartment: 'Apartamento',
    'Family Beach': 'Playa Familiar', Cove: 'Cala', 'Blue Flag': 'Bandera Azul', 'Nude Beach': 'Playa Naturista',
    'Beach Club': 'Beach Club',
    'Water Sports': 'Deportes Acuáticos', Hiking: 'Senderismo', 'Bike Rental': 'Alquiler Bicicletas',
    'Boat Tour': 'Paseo en Barco', Golf: 'Golf', 'Horse Riding': 'Equitación', Diving: 'Buceo',
    'Wine Tasting': 'Cata de Vinos',
    'Shopping Center': 'Centro Comercial', Fashion: 'Moda', Souvenirs: 'Recuerdos', 'Local Market': 'Mercado Local',
    'Wine Shop': 'Tienda de Vinos',
    Handyman: 'Manitas', Cleaning: 'Limpieza', Moving: 'Mudanzas', 'IT Support': 'Soporte Informático',
    Insurance: 'Seguros', Lawyer: 'Abogado', 'Tax Advisor': 'Asesor Fiscal', 'Real Estate': 'Inmobiliaria',
    Architect: 'Arquitecto', Photographer: 'Fotógrafo', 'Web Design': 'Diseño Web', Marketing: 'Marketing',
    'Car Rental': 'Alquiler Coche', Taxi: 'Taxi', 'Airport Transfer': 'Traslado Aeropuerto', 'Boat Rental': 'Alquiler Barco',
    Hospital: 'Hospital', Clinic: 'Clínica', Doctor: 'Médico', Dentist: 'Dentista',
    Optician: 'Óptica', Physiotherapy: 'Fisioterapia', 'Alternative Medicine': 'Medicina Alternativa',
  },
  en: {
    Italian: 'Italian', Spanish: 'Spanish', Asian: 'Asian', German: 'German', International: 'International',
    Pizza: 'Pizza', Sushi: 'Sushi', Tapas: 'Tapas', Seafood: 'Seafood', Brunch: 'Brunch',
    Vegetarian: 'Vegetarian', 'Fine Dining': 'Fine Dining',
    Coffee: 'Coffee', 'Tea House': 'Tea House', Bakery: 'Bakery', 'Cocktail Bar': 'Cocktail Bar', 'Wine Bar': 'Wine Bar',
    '5 Star': '5 Star', '4 Star': '4 Star', '3 Star': '3 Star',
    Boutique: 'Boutique', Resort: 'Resort', Agrotourism: 'Agrotourism', Apartment: 'Apartment',
    'Family Beach': 'Family Beach', Cove: 'Cove', 'Blue Flag': 'Blue Flag', 'Nude Beach': 'Nude Beach',
    'Beach Club': 'Beach Club',
    'Water Sports': 'Water Sports', Hiking: 'Hiking', 'Bike Rental': 'Bike Rental',
    'Boat Tour': 'Boat Tour', Golf: 'Golf', 'Horse Riding': 'Horse Riding', Diving: 'Diving',
    'Wine Tasting': 'Wine Tasting',
    'Shopping Center': 'Shopping Center', Fashion: 'Fashion', Souvenirs: 'Souvenirs', 'Local Market': 'Local Market',
    'Wine Shop': 'Wine Shop',
    Handyman: 'Handyman', Cleaning: 'Cleaning', Moving: 'Moving', 'IT Support': 'IT Support',
    Insurance: 'Insurance', Lawyer: 'Lawyer', 'Tax Advisor': 'Tax Advisor', 'Real Estate': 'Real Estate',
    Architect: 'Architect', Photographer: 'Photographer', 'Web Design': 'Web Design', Marketing: 'Marketing',
    'Car Rental': 'Car Rental', Taxi: 'Taxi', 'Airport Transfer': 'Airport Transfer', 'Boat Rental': 'Boat Rental',
    Hospital: 'Hospital', Clinic: 'Clinic', Doctor: 'Doctor', Dentist: 'Dentist',
    Optician: 'Optician', Physiotherapy: 'Physiotherapy', 'Alternative Medicine': 'Alternative Medicine',
  },
  de: {
    Italian: 'Italienisch', Spanish: 'Spanisch', Asian: 'Asiatisch', German: 'Deutsch', International: 'International',
    Pizza: 'Pizza', Sushi: 'Sushi', Tapas: 'Tapas', Seafood: 'Meeresfrüchte', Brunch: 'Brunch',
    Vegetarian: 'Vegetarisch', 'Fine Dining': 'Fine Dining',
    Coffee: 'Kaffee', 'Tea House': 'Teehaus', Bakery: 'Bäckerei', 'Cocktail Bar': 'Cocktailbar', 'Wine Bar': 'Weinbar',
    '5 Star': '5 Sterne', '4 Star': '4 Sterne', '3 Star': '3 Sterne',
    Boutique: 'Boutique', Resort: 'Resort', Agrotourism: 'Agrotourismus', Apartment: 'Apartment',
    'Family Beach': 'Familienstrand', Cove: 'Bucht', 'Blue Flag': 'Blaue Flagge', 'Nude Beach': 'FKK-Strand',
    'Beach Club': 'Strandclub',
    'Water Sports': 'Wassersport', Hiking: 'Wandern', 'Bike Rental': 'Fahrradverleih',
    'Boat Tour': 'Bootstour', Golf: 'Golf', 'Horse Riding': 'Reiten', Diving: 'Tauchen',
    'Wine Tasting': 'Weinprobe',
    'Shopping Center': 'Einkaufszentrum', Fashion: 'Mode', Souvenirs: 'Souvenirs', 'Local Market': 'Wochenmarkt',
    'Wine Shop': 'Weinhandlung',
    Handyman: 'Handwerker', Cleaning: 'Reinigung', Moving: 'Umzug', 'IT Support': 'IT-Support',
    Insurance: 'Versicherung', Lawyer: 'Rechtsanwalt', 'Tax Advisor': 'Steuerberater', 'Real Estate': 'Immobilien',
    Architect: 'Architekt', Photographer: 'Fotograf', 'Web Design': 'Webdesign', Marketing: 'Marketing',
    'Car Rental': 'Autovermietung', Taxi: 'Taxi', 'Airport Transfer': 'Flughafentransfer', 'Boat Rental': 'Bootsverleih',
    Hospital: 'Krankenhaus', Clinic: 'Klinik', Doctor: 'Arzt', Dentist: 'Zahnarzt',
    Optician: 'Optiker', Physiotherapy: 'Physiotherapie', 'Alternative Medicine': 'Alternative Medizin',
  },
  ru: {
    Italian: 'Итальянская', Spanish: 'Испанская', Asian: 'Азиатская', German: 'Немецкая', International: 'Интернациональная',
    Pizza: 'Пицца', Sushi: 'Суши', Tapas: 'Тапас', Seafood: 'Морепродукты', Brunch: 'Бранч',
    Vegetarian: 'Вегетарианская', 'Fine Dining': 'Высокая кухня',
    Coffee: 'Кофе', 'Tea House': 'Чайная', Bakery: 'Выпечка', 'Cocktail Bar': 'Коктейль-бар', 'Wine Bar': 'Винный бар',
    '5 Star': '5 Звёзд', '4 Star': '4 Звезды', '3 Star': '3 Звезды',
    Boutique: 'Бутик', Resort: 'Курорт', Agrotourism: 'Агротуризм', Apartment: 'Апартаменты',
    'Family Beach': 'Семейный пляж', Cove: 'Бухта', 'Blue Flag': 'Голубой флаг', 'Nude Beach': 'Нудистский пляж',
    'Beach Club': 'Пляжный клуб',
    'Water Sports': 'Водные виды', Hiking: 'Походы', 'Bike Rental': 'Прокат велосипедов',
    'Boat Tour': 'Экскурсия на лодке', Golf: 'Гольф', 'Horse Riding': 'Верховая езда', Diving: 'Дайвинг',
    'Wine Tasting': 'Дегустация вин',
    'Shopping Center': 'Торговый центр', Fashion: 'Мода', Souvenirs: 'Сувениры', 'Local Market': 'Местный рынок',
    'Wine Shop': 'Винный магазин',
    Handyman: 'Мастер', Cleaning: 'Уборка', Moving: 'Переезд', 'IT Support': 'IT-поддержка',
    Insurance: 'Страхование', Lawyer: 'Адвокат', 'Tax Advisor': 'Налоговый консультант', 'Real Estate': 'Недвижимость',
    Architect: 'Архитектор', Photographer: 'Фотограф', 'Web Design': 'Веб-дизайн', Marketing: 'Маркетинг',
    'Car Rental': 'Прокат авто', Taxi: 'Такси', 'Airport Transfer': 'Трансфер из аэропорта', 'Boat Rental': 'Аренда лодки',
    Hospital: 'Больница', Clinic: 'Клиника', Doctor: 'Врач', Dentist: 'Стоматолог',
    Optician: 'Оптика', Physiotherapy: 'Физиотерапия', 'Alternative Medicine': 'Альтернативная медицина',
  },
};
