import { create } from 'zustand';
import { persist } from 'zustand/middleware';

interface User {
  uid: string;
  email: string | null;
  displayName: string | null;
}

interface StoreState {
  language: 'es' | 'en' | 'de' | 'ru';
  favorites: string[];
  user: User | null;
  plannedDays: string[];
  setLanguage: (lang: 'es' | 'en' | 'de' | 'ru') => void;
  addToFavorites: (id: string) => void;
  removeFromFavorites: (id: string) => void;
  isFavorite: (id: string) => boolean;
  addToPlanned: (dayId: string) => void;
  removeFromPlanned: (dayId: string) => void;
  isPlanned: (dayId: string) => boolean;
  setUser: (user: User | null) => void;
}

export const useStore = create<StoreState>()(
  persist(
    (set, get) => ({
      language: 'en',
      favorites: [],
      user: null,
      plannedDays: [],
      setLanguage: (lang) => set({ language: lang }),
      addToFavorites: (id) => set((state) => ({ favorites: [...state.favorites, id] })),
      removeFromFavorites: (id) => set((state) => ({ favorites: state.favorites.filter((f) => f !== id) })),
      isFavorite: (id) => get().favorites.includes(id),
      addToPlanned: (dayId) => set((state) => ({ plannedDays: [...state.plannedDays, dayId] })),
      removeFromPlanned: (dayId) => set((state) => ({ plannedDays: state.plannedDays.filter((d) => d !== dayId) })),
      isPlanned: (dayId) => get().plannedDays.includes(dayId),
      setUser: (user) => set({ user }),
    }),
    { name: 'mallorca-storage' }
  )
);

export const translations = {
  es: {
    title: 'Directorio Mallorca',
    subtitle: 'Descubre los mejores negocios',
    search: 'Buscar...',
    categories: 'Categorías',
    favorites: 'Favoritos',
    profile: 'Perfil',
    language: 'Idioma',
    settings: 'Configuración',
    addToFavorites: 'Añadido a favoritos',
    removeFromFavorites: 'Eliminado de favoritos',
    verified: 'Verificado',
    loading: 'Cargando...',
    noBusinesses: 'No hay negocios',
    hours: 'Horario',
    noBusinessesInCategory: 'No hay negocios en esta categoría',
    noBusinessesInArea: 'No hay negocios en esta zona',
    areas: 'Zonas',
    businesses: 'Negocios',
    places: 'Lugares',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    signOut: 'Cerrar sesión',
    email: 'Correo electrónico',
    password: 'Contraseña',
    addBusiness: 'Añadir empresa',
    businessName: 'Nombre de la empresa',
    phone: 'Teléfono',
    website: 'Sitio web',
    description: 'Descripción',
    address: 'Dirección',
    submit: 'Enviar',
    about: 'Acerca de',
    version: 'Versión',
    privacy: 'Política de privacidad',
    help: 'Ayuda y soporte',
    events: 'Eventos',
    guides: 'Guías',
    tripPlanner: 'Planificador',
    premium: 'Premium',
    claim: 'Reclamar negocio',
    claimed: 'Reclamado',
    claimBusiness: '¿Es tuyo este negocio?',
    claimInfo: 'Verifica que eres el propietario y gestiona tus datos',
    claimRequested: 'Solicitud enviada',
    startDate: 'Fecha inicio',
    endDate: 'Fecha fin',
    allCategories: 'Todas las categorías',
    loadMore: 'Cargar más',
    noEvents: 'No hay eventos',
    noGuides: 'No hay guías',
    readMore: 'Leer más',
    planTrip: 'Planificar viaje',
    myPlans: 'Mis planes',
    addToPlan: 'Añadir al plan',
    removeFromPlan: 'Quitar del plan',
    day: 'Día',
    addDay: 'Añadir día',
    notes: 'Notas',
    premiumPartner: 'Partner Premium',
    claimNow: 'Reclamar ahora',
    callToAction: 'Llamar',
    getDirections: 'Cómo llegar',
    share: 'Compartir',
  },
  en: {
    title: 'Mallorca Directory',
    subtitle: 'Discover the best businesses',
    search: 'Search...',
    categories: 'Categories',
    favorites: 'Favorites',
    profile: 'Profile',
    language: 'Language',
    settings: 'Settings',
    addToFavorites: 'Added to favorites',
    removeFromFavorites: 'Removed from favorites',
    verified: 'Verified',
    loading: 'Loading...',
    noBusinesses: 'No businesses',
    hours: 'Hours',
    noBusinessesInCategory: 'No businesses in this category',
    noBusinessesInArea: 'No businesses in this area',
    areas: 'Areas',
    businesses: 'Businesses',
    places: 'Places',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    email: 'Email',
    password: 'Password',
    addBusiness: 'Add Business',
    businessName: 'Business Name',
    phone: 'Phone',
    website: 'Website',
    description: 'Description',
    address: 'Address',
    submit: 'Submit',
    about: 'About',
    version: 'Version',
    privacy: 'Privacy Policy',
    help: 'Help & Support',
    events: 'Events',
    guides: 'Guides',
    tripPlanner: 'Trip Planner',
    premium: 'Premium',
    claim: 'Claim Business',
    claimed: 'Claimed',
    claimBusiness: 'Is this yours?',
    claimInfo: 'Verify ownership and manage your data',
    claimRequested: 'Request submitted',
    startDate: 'Start Date',
    endDate: 'End Date',
    allCategories: 'All Categories',
    loadMore: 'Load More',
    noEvents: 'No events found',
    noGuides: 'No guides yet',
    readMore: 'Read More',
    planTrip: 'Plan Your Trip',
    myPlans: 'My Plans',
    addToPlan: 'Add to Plan',
    removeFromPlan: 'Remove from Plan',
    day: 'Day',
    addDay: 'Add Day',
    notes: 'Notes',
    premiumPartner: 'Premium Partner',
    claimNow: 'Claim Now',
    callToAction: 'Call',
    getDirections: 'Get Directions',
    share: 'Share',
  },
  de: {
    title: 'Mallorca Verzeichnis',
    subtitle: 'Entdecken Sie die besten Geschäfte',
    search: 'Suchen...',
    categories: 'Kategorien',
    favorites: 'Favoriten',
    profile: 'Profil',
    language: 'Sprache',
    settings: 'Einstellungen',
    addToFavorites: 'Zu Favoriten hinzugefügt',
    removeFromFavorites: 'Aus Favoriten entfernt',
    verified: 'Verifiziert',
    loading: 'Wird geladen...',
    noBusinesses: 'Keine Unternehmen',
    hours: 'Öffnungszeiten',
    noBusinessesInCategory: 'Keine Unternehmen in dieser Kategorie',
    noBusinessesInArea: 'Keine Unternehmen in diesem Bereich',
    areas: 'Gebiete',
    businesses: 'Unternehmen',
    places: 'Orte',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    signOut: 'Abmelden',
    email: 'E-Mail',
    password: 'Passwort',
    addBusiness: 'Unternehmen hinzufügen',
    businessName: 'Unternehmensname',
    phone: 'Telefon',
    website: 'Webseite',
    description: 'Beschreibung',
    address: 'Adresse',
    submit: 'Absenden',
    about: 'Über',
    version: 'Version',
    privacy: 'Datenschutz',
    help: 'Hilfe & Support',
    events: 'Veranstaltungen',
    guides: 'Ratgeber',
    tripPlanner: 'Reiseplaner',
    premium: 'Premium',
    claim: 'Unternehmen beanspruchen',
    claimed: 'Beansprucht',
    claimBusiness: 'Gehört Ihnen das?',
    claimInfo: 'Bestätigen Sie Ihre Inhaberschaft und verwalten Sie Ihre Daten',
    claimRequested: 'Anfrage gesendet',
    startDate: 'Startdatum',
    endDate: 'Enddatum',
    allCategories: 'Alle Kategorien',
    loadMore: 'Mehr laden',
    noEvents: 'Keine Veranstaltungen',
    noGuides: 'Keine Ratgeber',
    readMore: 'Weiterlesen',
    planTrip: 'Reise planen',
    myPlans: 'Meine Pläne',
    addToPlan: 'Zum Plan hinzufügen',
    removeFromPlan: 'Vom Plan entfernen',
    day: 'Tag',
    addDay: 'Tag hinzufügen',
    notes: 'Notizen',
    premiumPartner: 'Premium Partner',
    claimNow: 'Jetzt beanspruchen',
    callToAction: 'Anrufen',
    getDirections: 'Route',
    share: 'Teilen',
  },
  ru: {
    title: 'Директория Майорки',
    subtitle: 'Откройте лучшие заведения',
    search: 'Поиск...',
    categories: 'Категории',
    favorites: 'Избранное',
    profile: 'Профиль',
    language: 'Язык',
    settings: 'Настройки',
    addToFavorites: 'Добавлено в избранное',
    removeFromFavorites: 'Удалено из избранного',
    verified: 'Проверено',
    loading: 'Загрузка...',
    noBusinesses: 'Нет заведений',
    hours: 'Часы работы',
    noBusinessesInCategory: 'Нет заведений в этой категории',
    noBusinessesInArea: 'Нет заведений в этой зоне',
    areas: 'Районы',
    businesses: 'Заведения',
    places: 'Места',
    signIn: 'Войти',
    signUp: 'Регистрация',
    signOut: 'Выйти',
    email: 'Email',
    password: 'Пароль',
    addBusiness: 'Добавить компанию',
    businessName: 'Название компании',
    phone: 'Телефон',
    website: 'Сайт',
    description: 'Описание',
    address: 'Адрес',
    submit: 'Отправить',
    about: 'О приложении',
    version: 'Версия',
    privacy: 'Политика конфиденциальности',
    help: 'Помощь и поддержка',
    events: 'События',
    guides: 'Гайды',
    tripPlanner: 'Планировщик',
    premium: 'Премиум',
    claim: 'Заявить бизнес',
    claimed: 'Заявлено',
    claimBusiness: 'Это ваш бизнес?',
    claimInfo: 'Подтвердите владение и управляйте данными',
    claimRequested: 'Запрос отправлен',
    startDate: 'Дата начала',
    endDate: 'Дата окончания',
    allCategories: 'Все категории',
    loadMore: 'Загрузить ещё',
    noEvents: 'Нет событий',
    noGuides: 'Нет гайдов',
    readMore: 'Читать далее',
    planTrip: 'Спланировать поездку',
    myPlans: 'Мои планы',
    addToPlan: 'Добавить в план',
    removeFromPlan: 'Убрать из плана',
    day: 'День',
    addDay: 'Добавить день',
    notes: 'Заметки',
    premiumPartner: 'Премиум-партнёр',
    claimNow: 'Заявить сейчас',
    callToAction: 'Позвонить',
    getDirections: 'Маршрут',
    share: 'Поделиться',
  },
};

export const categoryTranslations: Record<string, Record<string, string>> = {
  es: {
    restaurants: 'Restaurantes', cafes: 'Cafeterías', hotels: 'Hoteles',
    beaches: 'Playas', parks: 'Parques', activities: 'Actividades',
    shopping: 'Tiendas', supermarkets: 'Supermercados', services: 'Servicios',
    transport: 'Transporte', health: 'Hospitales', pharmacies: 'Farmacias',
    police: 'Policía', gasstations: 'Gasolineras', veterinarians: 'Veterinarios',
    banks: 'Bancos', postoffice: 'Correos', industrial: 'Polígonos Industriales',
  },
  en: {
    restaurants: 'Restaurants', cafes: 'Cafés', hotels: 'Hotels',
    beaches: 'Beaches', parks: 'Parks', activities: 'Activities',
    shopping: 'Shopping', supermarkets: 'Supermarkets', services: 'Services',
    transport: 'Transport', health: 'Hospitals', pharmacies: 'Pharmacies',
    police: 'Police', gasstations: 'Gas Stations', veterinarians: 'Veterinarians',
    banks: 'Banks', postoffice: 'Post Office', industrial: 'Industrial Estates',
  },
  de: {
    restaurants: 'Restaurants', cafes: 'Cafés', hotels: 'Hotels',
    beaches: 'Strände', parks: 'Parks', activities: 'Aktivitäten',
    shopping: 'Einkaufen', supermarkets: 'Supermärkte', services: 'Dienstleistungen',
    transport: 'Verkehr', health: 'Krankenhäuser', pharmacies: 'Apotheken',
    police: 'Polizei', gasstations: 'Tankstellen', veterinarians: 'Tierärzte',
    banks: 'Banken', postoffice: 'Post', industrial: 'Industriegebiete',
  },
  ru: {
    restaurants: 'Рестораны', cafes: 'Кафе', hotels: 'Отели',
    beaches: 'Пляжи', parks: 'Парки', activities: 'Развлечения',
    shopping: 'Магазины', supermarkets: 'Супермаркеты', services: 'Услуги',
    transport: 'Транспорт', health: 'Больницы', pharmacies: 'Аптеки',
    police: 'Полиция', gasstations: 'Заправки', veterinarians: 'Ветеринары',
    banks: 'Банки', postoffice: 'Почта', industrial: 'Промышленные зоны',
  },
};

export const subcategoryTranslations: Record<string, Record<string, string>> = {
  es: {
    Italian: 'Italiano', Spanish: 'Español', Asian: 'Asiático', German: 'Alemán', International: 'Internacional',
    Pizza: 'Pizza', Sushi: 'Sushi', Tapas: 'Tapas', Seafood: 'Mariscos', Brunch: 'Brunch',
    Vegetarian: 'Vegetariano', 'Fine Dining': 'Alta Cocina',
    Coffee: 'Café', 'Tea House': 'Casa de Té', Bakery: 'Panadería', 'Cocktail Bar': 'Coctelería', 'Wine Bar': 'Bar de Vinos',
    '5 Star': '5 Estrellas', '4 Star': '4 Estrellas', '3 Star': '3 Estrellas',
    Boutique: 'Boutique', Resort: 'Complejo Turístico', Agrotourism: 'Agroturismo', Apartment: 'Apartamento',
    'Family Beach': 'Playa Familiar', Cove: 'Cala', 'Blue Flag': 'Bandera Azul', 'Nude Beach': 'Playa Naturista',
    'Beach Club': 'Beach Club',
    'Water Sports': 'Deportes Acuáticos', Hiking: 'Senderismo', 'Bike Rental': 'Alquiler Bicicletas',
    'Boat Tour': 'Paseo en Barco', Golf: 'Golf', 'Horse Riding': 'Equitación', Diving: 'Buceo',
    'Wine Tasting': 'Cata de Vinos',
    'Shopping Center': 'Centro Comercial', Fashion: 'Moda', Souvenirs: 'Recuerdos', 'Local Market': 'Mercado Local',
    'Wine Shop': 'Tienda de Vinos',
    Handyman: 'Manitas', Cleaning: 'Limpieza', Moving: 'Mudanzas', 'IT Support': 'Soporte Informático',
    Insurance: 'Seguros', Lawyer: 'Abogado', 'Tax Advisor': 'Asesor Fiscal', 'Real Estate': 'Inmobiliaria',
    Architect: 'Arquitecto', Photographer: 'Fotógrafo', 'Web Design': 'Diseño Web', Marketing: 'Marketing',
    'Car Rental': 'Alquiler Coche', Taxi: 'Taxi', 'Airport Transfer': 'Traslado Aeropuerto', 'Boat Rental': 'Alquiler Barco',
    Hospital: 'Hospital', Clinic: 'Clínica', Doctor: 'Médico', Dentist: 'Dentista',
    Optician: 'Óptica', Physiotherapy: 'Fisioterapia', 'Alternative Medicine': 'Medicina Alternativa',
  },
  en: {
    Italian: 'Italian', Spanish: 'Spanish', Asian: 'Asian', German: 'German', International: 'International',
    Pizza: 'Pizza', Sushi: 'Sushi', Tapas: 'Tapas', Seafood: 'Seafood', Brunch: 'Brunch',
    Vegetarian: 'Vegetarian', 'Fine Dining': 'Fine Dining',
    Coffee: 'Coffee', 'Tea House': 'Tea House', Bakery: 'Bakery', 'Cocktail Bar': 'Cocktail Bar', 'Wine Bar': 'Wine Bar',
    '5 Star': '5 Star', '4 Star': '4 Star', '3 Star': '3 Star',
    Boutique: 'Boutique', Resort: 'Resort', Agrotourism: 'Agrotourism', Apartment: 'Apartment',
    'Family Beach': 'Family Beach', Cove: 'Cove', 'Blue Flag': 'Blue Flag', 'Nude Beach': 'Nude Beach',
    'Beach Club': 'Beach Club',
    'Water Sports': 'Water Sports', Hiking: 'Hiking', 'Bike Rental': 'Bike Rental',
    'Boat Tour': 'Boat Tour', Golf: 'Golf', 'Horse Riding': 'Horse Riding', Diving: 'Diving',
    'Wine Tasting': 'Wine Tasting',
    'Shopping Center': 'Shopping Center', Fashion: 'Fashion', Souvenirs: 'Souvenirs', 'Local Market': 'Local Market',
    'Wine Shop': 'Wine Shop',
    Handyman: 'Handyman', Cleaning: 'Cleaning', Moving: 'Moving', 'IT Support': 'IT Support',
    Insurance: 'Insurance', Lawyer: 'Lawyer', 'Tax Advisor': 'Tax Advisor', 'Real Estate': 'Real Estate',
    Architect: 'Architect', Photographer: 'Photographer', 'Web Design': 'Web Design', Marketing: 'Marketing',
    'Car Rental': 'Car Rental', Taxi: 'Taxi', 'Airport Transfer': 'Airport Transfer', 'Boat Rental': 'Boat Rental',
    Hospital: 'Hospital', Clinic: 'Clinic', Doctor: 'Doctor', Dentist: 'Dentist',
    Optician: 'Optician', Physiotherapy: 'Physiotherapy', 'Alternative Medicine': 'Alternative Medicine',
  },
  de: {
    Italian: 'Italienisch', Spanish: 'Spanisch', Asian: 'Asiatisch', German: 'Deutsch', International: 'International',
    Pizza: 'Pizza', Sushi: 'Sushi', Tapas: 'Tapas', Seafood: 'Meeresfrüchte', Brunch: 'Brunch',
    Vegetarian: 'Vegetarisch', 'Fine Dining': 'Fine Dining',
    Coffee: 'Kaffee', 'Tea House': 'Teehaus', Bakery: 'Bäckerei', 'Cocktail Bar': 'Cocktailbar', 'Wine Bar': 'Weinbar',
    '5 Star': '5 Sterne', '4 Star': '4 Sterne', '3 Star': '3 Sterne',
    Boutique: 'Boutique', Resort: 'Resort', Agrotourism: 'Agrotourismus', Apartment: 'Apartment',
    'Family Beach': 'Familienstrand', Cove: 'Bucht', 'Blue Flag': 'Blaue Flagge', 'Nude Beach': 'FKK-Strand',
    'Beach Club': 'Strandclub',
    'Water Sports': 'Wassersport', Hiking: 'Wandern', 'Bike Rental': 'Fahrradverleih',
    'Boat Tour': 'Bootstour', Golf: 'Golf', 'Horse Riding': 'Reiten', Diving: 'Tauchen',
    'Wine Tasting': 'Weinprobe',
    'Shopping Center': 'Einkaufszentrum', Fashion: 'Mode', Souvenirs: 'Souvenirs', 'Local Market': 'Wochenmarkt',
    'Wine Shop': 'Weinhandlung',
    Handyman: 'Handwerker', Cleaning: 'Reinigung', Moving: 'Umzug', 'IT Support': 'IT-Support',
    Insurance: 'Versicherung', Lawyer: 'Rechtsanwalt', 'Tax Advisor': 'Steuerberater', 'Real Estate': 'Immobilien',
    Architect: 'Architekt', Photographer: 'Fotograf', 'Web Design': 'Webdesign', Marketing: 'Marketing',
    'Car Rental': 'Autovermietung', Taxi: 'Taxi', 'Airport Transfer': 'Flughafentransfer', 'Boat Rental': 'Bootsverleih',
    Hospital: 'Krankenhaus', Clinic: 'Klinik', Doctor: 'Arzt', Dentist: 'Zahnarzt',
    Optician: 'Optiker', Physiotherapy: 'Physiotherapie', 'Alternative Medicine': 'Alternative Medizin',
  },
  ru: {
    Italian: 'Итальянская', Spanish: 'Испанская', Asian: 'Азиатская', German: 'Немецкая', International: 'Интернациональная',
    Pizza: 'Пицца', Sushi: 'Суши', Tapas: 'Тапас', Seafood: 'Морепродукты', Brunch: 'Бранч',
    Vegetarian: 'Вегетарианская', 'Fine Dining': 'Высокая кухня',
    Coffee: 'Кофе', 'Tea House': 'Чайная', Bakery: 'Выпечка', 'Cocktail Bar': 'Коктейль-бар', 'Wine Bar': 'Винный бар',
    '5 Star': '5 Звёзд', '4 Star': '4 Звезды', '3 Star': '3 Звезды',
    Boutique: 'Бутик', Resort: 'Курорт', Agrotourism: 'Агротуризм', Apartment: 'Апартаменты',
    'Family Beach': 'Семейный пляж', Cove: 'Бухта', 'Blue Flag': 'Голубой флаг', 'Nude Beach': 'Нудистский пляж',
    'Beach Club': 'Пляжный клуб',
    'Water Sports': 'Водные виды', Hiking: 'Походы', 'Bike Rental': 'Прокат велосипедов',
    'Boat Tour': 'Экскурсия на лодке', Golf: 'Гольф', 'Horse Riding': 'Верховая езда', Diving: 'Дайвинг',
    'Wine Tasting': 'Дегустация вин',
    'Shopping Center': 'Торговый центр', Fashion: 'Мода', Souvenirs: 'Сувениры', 'Local Market': 'Местный рынок',
    'Wine Shop': 'Винный магазин',
    Handyman: 'Мастер', Cleaning: 'Уборка', Moving: 'Переезд', 'IT Support': 'IT-поддержка',
    Insurance: 'Страхование', Lawyer: 'Адвокат', 'Tax Advisor': 'Налоговый консультант', 'Real Estate': 'Недвижимость',
    Architect: 'Архитектор', Photographer: 'Фотограф', 'Web Design': 'Веб-дизайн', Marketing: 'Маркетинг',
    'Car Rental': 'Прокат авто', Taxi: 'Такси', 'Airport Transfer': 'Трансфер из аэропорта', 'Boat Rental': 'Аренда лодки',
    Hospital: 'Больница', Clinic: 'Клиника', Doctor: 'Врач', Dentist: 'Стоматолог',
    Optician: 'Оптика', Physiotherapy: 'Физиотерапия', 'Alternative Medicine': 'Альтернативная медицина',
  },
};
