export const categories = [
  { id: 'restaurants', name: 'Restaurants', emoji: '🍽️', color: '#fef2f2' },
  { id: 'cafes', name: 'Cafes', emoji: '☕', color: '#fef3c7' },
  { id: 'hotels', name: 'Hotels', emoji: '🏨', color: '#dbeafe' },
  { id: 'beaches', name: 'Beaches', emoji: '🏖️', color: '#fef9c3' },
  { id: 'parks', name: 'Parks & Gardens', emoji: '🌳', color: '#dcfce7' },
  { id: 'activities', name: 'Activities', emoji: '🎯', color: '#e9d5ff' },
  { id: 'shopping', name: 'Shopping', emoji: '🛍️', color: '#fce7f3' },
  { id: 'supermarkets', name: 'Supermarkets', emoji: '🛒', color: '#f0fdf4' },
  { id: 'services', name: 'Services', emoji: '🔧', color: '#f3f4f6' },
  { id: 'transport', name: 'Transport', emoji: '🚗', color: '#e0e7ff' },
  { id: 'health', name: 'Hospitals & Clinics', emoji: '🏥', color: '#dcfce7' },
  { id: 'pharmacies', name: 'Pharmacies', emoji: '💊', color: '#f0fdf4' },
  { id: 'police', name: 'Police & Emergency', emoji: '👮', color: '#eff6ff' },
  { id: 'gasstations', name: 'Gas Stations', emoji: '⛽', color: '#fefce8' },
  { id: 'veterinarians', name: 'Veterinarians', emoji: '🐾', color: '#f5f3ff' },
  { id: 'banks', name: 'Banks & ATMs', emoji: '🏦', color: '#f3f4f6' },
  { id: 'postoffice', name: 'Post Office', emoji: '📮', color: '#fef2f2' },
  { id: 'industrial', name: 'Industrial Estates', emoji: '🏭', color: '#f3e8ff' },
];
